### ISSUE TITLE
Compilation error for directory output directive

### ISSUE THREAD

**Issue by byoo** [KolmogorovLab/Lumos#1]
Hello, I'd like to report that nextflow 24.10.1 couldn't compile the workflow. This looks to be caused by the change in nextflow `24.10`

https://nextflow.io/docs/latest/workflow.html#migrating-from-first-preview

_The directory output directive has been replaced with the outputDir config option and -output-dir command line option, which is results by default. The other directives such as mode have been replaced with config options under workflow.output.*._

```
$ /software/nextflow/current/nextflow tumorNormalONT.nf 

 N E X T F L O W   ~  version 24.10.1

Launching `tumorNormalONT.nf` [happy_bhaskara] DSL2 - revision: 09395b075e

ERROR ~ Script compilation error
- file : /home/byoo/src/longread_somatic_nf/tumorNormalONT.nf
- cause: Invalid publish target definition @ line 88, column 5.
       directory params.outdir
       ^

1 error
```

**Comment by mikolmogorov** [comment]
Should work with 24.10 now!
